from typing import Protocol
from recipe_manager.io.output_handler import OutputHandler


class InputHandler(Protocol):
    output_handler: OutputHandler

    def get_string(self, prompt: str) -> str: ...

    def get_optional_string(self, prompt: str) -> str | None: ...

    def get_yes_no(self, prompt: str, default: bool | None = None) -> bool | None: ...

    def get_int(self, prompt: str) -> int: ...

    def get_float(self, prompt: str) -> float: ...

    def get_int_in_range(self, prompt: str, min_val: int, max_val: int) -> int: ...
