from dataclasses import dataclass
from typing import Protocol


@dataclass
class InputHandler(Protocol):
    def get_string(self, prompt: str) -> str: ...

    def get_optional_string(self, prompt: str) -> str | None: ...

    def get_yes_no(self, prompt: str) -> bool: ...

    def get_int(self, prompt: str) -> int: ...

    def get_float(self, prompt: str) -> float: ...

    def get_int_in_range(self, prompt: str, min_val: int, max_val: int) -> int: ...
